### PR TITLE
Upgraded to new polymer element template, added documentation

### PR DESCRIPTION
**Pull request by zmoshansky**
Updating to follow the latest recommendations for [polymer 1.0 elements](https://www.polymer-project.org/1.0/docs/start/reusableelements.html).

- Fixed dependency on polymer.html to function correctly when imported into another project [example](https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L10)
- Removed Package.json and dependencies on gulp, browsersync
- Moved dependency on fonts-roboto to dev only
- Added standardized [documentation page](https://zmoshansky.github.io/paper-share-buttons/components/paper-share-buttons/) (autogenerated: see https://www.polymer-project.org/1.0/docs/start/reusableelements.htm)
- Refactored Url handling to share a particular href if given

### CODE REVIEW

**Comment by grvcoelho** [comment]
Good! Is evertything still working?

**Comment by zmoshansky** [comment]
Works fine on my machine (tm). Trying the demo page also yields the
expected results.

**Comment by zmoshansky** [comment]
I also have an updated `gh-pages` branch, but I'm unable to make a PR, likewise for the version tag. Alternatively, the steps were very easy. [Instructions](https://www.polymer-project.org/1.0/docs/start/reusableelements.html#publishing-a-demo-and-landing-page-for-your-element)

**Comment by grvcoelho** [comment]
I'll do it :smile:

**Pull request merged**
